api/urls.py
#path('api/load_more/', views.load_more, name='load_more'),
"""
URL configuration for blocks project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.urls import path
from api import views

app_name = "api"

urlpatterns = [
   path('load_more/', views.load_more, name='load_more'),
]

posts/urls.py
from django.urls import path, include
from posts import views

app_name = "posts"

urlpatterns = [
    path("post/", views.post, name = "post"),
    path("commentary/", views.commentary, name = "commentary"),
    path("follow/", views.follow, name = "follow"),
    path("unfollow/", views.unfollow, name="unfollow"),
    path("post_like/", views.post_like, name="post_like"),
    path("post_unlike/", views.post_unlike, name = "post_unlike"),
]

user/urls.py
from django.urls import path, include
from user import views


urlpatterns = [
    path("login/",views.login, name = "login"),
    path("register/", views.register, name = "register"),
    path("logout/", views.logout, name = "logout"),
    path("u/<slug:username>", views.profile, name = "profile"),
    path("action/change_avatar/", views.change_avatar, name = "change_avatar")

]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser



class Users(AbstractUser):
    image = models.ImageField(upload_to="user/avatars", null=True, blank=True, verbose_name="Аватар", default="/static/img/avatar-fat.jpg")

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.username
    
class Follow(models.Model):
    follower = models.ForeignKey(Users, on_delete=models.CASCADE, verbose_name="Подписчик", related_name='follower') #related_name='follows' ! can be bugs
    target = models.ForeignKey(Users, on_delete=models.CASCADE,verbose_name="Цель подписки", related_name='target') #related_name='follows' ! can be bugs

    class Meta:
        verbose_name = "Подписка"
        verbose_name_plural = "Подписки"
    
    def __str__(self):
        return f"Подписка {self.follower} на {self.target}"

user/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from main.utils import publish_to_brocker
from user.forms import UserLoginForm, UserRegisterForm
from django.contrib import auth
from blocks.settings import DEBUG
from user.models import Users, Follow
from posts.models import Posts, Commentaries
from main.caching import *
import json



# Create your views here.


def login(request):

    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("user:profile", kwargs={"username":request.user.username}))


    #DEBUG LOGIC
    if DEBUG:
        print("method =", request.method)
        if request.method == "POST":
            print("username =", request.POST["username"])
            print("password =", request.POST["password"])
        else:
            print(request.GET)
    #DEBUG LOGIC


    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST["username"]
            password = request.POST["password"]
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse("main:index"))


    else:
        form = UserLoginForm()





    
    context = {
        "form":form
    }

    return render(request, "user/login.html", context)

def register(request):

    if request.method == "POST":
        form = UserRegisterForm(data = request.POST)
        if form.is_valid():

        


            form.save()
            
            user = auth.authenticate(username=request.POST["username"], password=request.POST["password1"])
            if user:

                #to rabit mq

                data = {
                    "username":request.POST["username"],
                    "password":user.password,
                    "email":request.POST["email"],
                    "first_name":request.POST["first_name"],
                    "last_name":request.POST["last_name"]
                }

                body = json.dumps(data)

                try:
                    publish_to_brocker("localhost", "blocks-ex-direct-all", body)
                except:
                    #save on the temporary storage
                    print("Cannot publish to brocker")
                #

                auth.login(request, user)
                return HttpResponseRedirect(reverse("user:profile", kwargs={"username":request.user.username}))
            

    else:
        form = UserRegisterForm()



    context = {
        "form":form

    }

    return render(request, "user/register.html", context)


def change_avatar(request):

    if not request.user.is_authenticated:
        #NOT AUTH LOGIC
        return HttpResponseRedirect(reverse("user:login"))

    user = request.user


    try:
        redirect = request.META.get('HTTP_REFERER')
    except:
        redirect = reverse("main:index")

    return HttpResponseRedirect(redirect)




def profile(request, username):


    user = Users.objects.get(username = username)

    if user == None:
        #Пользователь не найден
        #redirect
        return HttpResponseRedirect(reverse("main:index"))
    
    
    posts = Posts.objects.all().filter(user = user).order_by("-posting_time")
    has_posts = len(posts) > 0
    posts_num = len(posts)

    follows = Follow.objects.all().filter(follower = user)
    follows_num = len(follows)

    followers = Follow.objects.all().filter(target = user)
    followers_num = len(followers)

    if request.user.is_authenticated:
        is_followed = len(Follow.objects.filter(follower = request.user, target = user)) > 0
    else:
        is_followed = False


    view_as = "" #owner, follower, default
    #to do!!!!!

    is_owner = user == request.user


    context = {
        "user":user,
        "posts":posts,
        "has_posts":has_posts,
        "posts_num":posts_num,
        "follows_num":follows_num,
        "followers_num":followers_num,
        "is_followed":is_followed,
        "is_owner":is_owner
    }

    return render(request, "user/profile.html", context)


def logout(request):
    print(request)
    auth.logout(request)

    return HttpResponseRedirect(reverse("user:login"))

user/templates/user/profile.html
{% extends "main/base.html" %}
{% load static %}
{% load get_commentaries %}
{% load get_time_difference %}


{% block title %}
<title>Профиль {{user.username}}</title>
{% endblock title %}


{% block content %}
<link rel="stylesheet" href="{% static "users/profile/style.css" %}">
	<!--Navbar-->
	<nav class="navbar navbar-fixed navbar-dark info-color">
    </div>
    </div>
	</nav>
	<!--/.Navbar-->

	<main>

		<div class="container_bio">

			<div class = "user_bio">

				<div class = "leftside_user_bio">
					<div class="row m-b-r m-t-3">
                    {% if is_owner %}
                        <div class="user_image_div">
                            <a href = {% url "user:change_avatar" %}><img src="{{user.image}}" alt="" class="user_image"></a>
                        </div>
                    {% else %}
                        <div class="user_image_div">
                            <img src="{{user.image}}" alt="" class="user_image">
                        </div>
                    {% endif %}


						<div class="col-md-9 p-t-2">
							{% if is_followed %}
							<form> <h2 class="h2-responsive">@{{user.username}}<a type="button" href = {% url "posts:unfollow" %}?username={{user.username}} class="btn btn-info-outline waves-effect">Unfollow</a></h2> </form> 
                            {% elif is_owner %}

							{% else %}
							<form> <h2 class="h2-responsive">@{{user.username}}<a type="button" href = {% url "posts:follow" %}?username={{user.username}} class="btn btn-info-outline waves-effect">Follow</a></h2> </form> 
							{% endif %}
							
							<p>{{user.first_name}} {{user.last_name}}</p>
							<p>Description</p>
						</div>
					</div>
					
					<div class = "bio_other_info">
						<strong>{{posts_num}} posts</strong> <strong class = "followers">{{followers_num}} followers</strong> <strong> {{follows_num}} follow</strong>
					</div>

				</div>		

				{% comment %} <div class = "rightside_user_bio">
						<ul class="flex-menu">
							<li><strong>{{posts_num}}</strong> posts</li>
							<li><strong>{{followers_num}}</strong> followers</li>
							<li><strong>{{follows_num}}</strong> following</li>
						</ul>
				</div> {% endcomment %}

			</div>

		</div>
			
		


		{% comment %} END BIO {% endcomment %}

		{% if has_posts %}                           
        {% for post in posts %}

        <div class="card-body">

            <div class="media">
                <img src="{{post.user.image}}" alt="img" width="60px" height="60px" class="rounded-circle mr-3">
        
            <div class="media-body">
                    <a href="{% url "user:profile" post.user.username %}" class = "username_text">{{post.user.username}}</a>
                    <p class="text-justify">{{post.text}}</p>
                    

                    <div class = "user_actions">

                        <form class = "commentary_input" metod = "GET" action = "{% url "posts:commentary" %}">
                            <div class = "custom_commentary_text">

                                <div class = "like">
                                    <a href={% url "posts:post_like" %}?id={{post.id}} class="like_button">
                                        <img src = "{% static "main/like_button/black_heart.svg" %}" height = 30px, width = 30px>
                                    </a>
                                </div>

    
                                <input type="text" name="message" id="message" placeholder="Commentary" class="commentary_input_text">
                                <input type="hidden" name="post_id" value="{{post.id}}">
                                
                                
                                
                                <script>
                                    function myFunction() {

                                        var posts = document.getElementById('post_commentaries')
                                    
                                        if (posts.style.display == "none"){
                                            posts.style.display = "block"
                                        }else{
                                            posts.style.display = "none"
                                        }
                                    
                                      } 
                                </script>

                                <form>
                                    <button type = "button" class = "comment_button" onclick="myFunction()">
                                        <img src = "{% static "main/comment_button/comment-solid.svg" %}" height = 30px, width = 30px>
                                    </button>
                                </form>
                            </div>
                        </form>
    
                    </div>
                    
                    
                <div class = "post_commentaries" id = "post_commentaries" style="display:none">
                    {% comment %} commentaries {% endcomment %}
                    {% get_commentaries post as commentaries %}
                    <p class = "commentaries">
                        {% for commentary in commentaries %}
                            <div class="media">
                                <img src="{{commentary.user.image}}" alt="img" width="30px" height="30px" class="rounded-circle mr-2">
                                <div class="media-body">
                                        <p class="card-text text-justify">{{commentary.user.username}}: {{commentary.text}}</p>

                                </div>


                            </div>
                        {% endfor %}
                    </p>    
                    {% comment %} commentaries {% endcomment %}

                </div>
            
                

            </div>




            <small>{%get_time_difference post.posting_time%}</small>

            </div>





            </div>
            <hr>

        {% endfor %}

            {% comment %} pagination {% endcomment %}

           
            
            {% comment %}  {% endcomment %}


    {% else %}
    <p>Постов нет<p>
    {% endif %}  



{% endblock content %}

user/templates/user/profile2.html
<!DOCTYPE html>
{% extends "main/base.html" %}
{% load static %}
{% load get_commentaries %}
{% load get_time_difference %}
<link rel="stylesheet" href="{% static "users/profile/style.css" %}">
<link rel="stylesheet" href="{% static "main/style.css" %}">

{% block title %}
    <title>{{title}}</title>
{% endblock title %}


{% block content %}
        <!---------------------------------------Middle columns  start---------------->



        <div class="container_bio">

			<div class = "user_bio">

				<div class = "leftside_user_bio">
					<div class="row m-b-r m-t-3">

						<div class="user_image_div">
							<img src="{{user.image}}" alt="" class="user_image">
						</div>

						<div class="col-md-9 p-t-2">
							<form> <h2 class="h2-responsive">@{{user.username}}<button disabled type="button" value="user.username"  formmethod = "GET" formaction = "{% url "posts:follow"%}" class="btn btn-info-outline waves-effect">Follow</button></h2> </form> 
							<p>{{user.first_name}} {{user.last_name}}</p>
							<p>Description</p>
						</div>
					</div>
					
					<div class = "bio_other_info">
						<strong>{{posts_num}} posts</strong> <strong class = "followers">{{followers_num}} followers</strong> <strong> {{follows_num}} follow</strong>
					</div>

				</div>		

				{% comment %} <div class = "rightside_user_bio">
						<ul class="flex-menu">
							<li><strong>{{posts_num}}</strong> posts</li>
							<li><strong>{{followers_num}}</strong> followers</li>
							<li><strong>{{follows_num}}</strong> following</li>
						</ul>
				</div> {% endcomment %}

			</div>

		</div>
			




    {% if has_posts %}                           
    {% for post in posts %}

    <div class="card-body">

        <div class="media">
            <img src="{{post.user.image}}" alt="img" width="55px" height="55px" class="rounded-circle mr-3">

        <div class="media-body">
                <a href="{% url "user:profile" post.user.username %}" class = "username_text">{{post.user.username}}</a>
                <p class="text-justify">{{post.text}}</p>
                


                
            {% comment %} commentaries {% endcomment %}
            {% get_commentaries post as commentaries %}
            <p class = "commentaries">
                {% for commentary in commentaries %}
                    <div class="media">
                        <img src="{{commentary.user.image}}" alt="img" width="25px" height="25px" class="rounded-circle mr-2">
                        <div class="media-body">
                                <p class="card-text text-justify">{{commentary.user.username}}: {{commentary.text}}</p>

                        </div>


                    </div>
                {% endfor %}
            </p>    
            {% comment %} commentaries {% endcomment %}

           


            <form class = "commentary_input" metod = "GET" action = "{% url "posts:commentary" %}">
                <input type="text" name="message" id="message" placeholder="Commentary" class="form-control form-control-md">
                <input type="hidden" name="post_id" value="{{post.id}}">
            </form>


        </div>

        <small>{%get_time_difference post.posting_time%}</small>

        </div>





        </div>
        <hr>

    {% endfor %}
{% else %}
<p>Постов нет<p>
{% endif %} 











{% endblock content %}


{% comment %} 
{% block left_column %}
<div class="col-12 col-lg-3">

    <div class="left-column">


        <div class="card card-left1 mb-4" >
            <img src="{% static "img/photo-1455448972184-de647495d428.jpg" %}" alt="" class="card-img-top img-fluid">
            <div class="card-body text-center ">
                <img src="{% static "img/avatar-dhg.png" %}" alt="img" width="120px" height="120px" class="rounded-circle mt-n5">
                <h5 class="card-title">Dave Gamache</h5>
                <p class="card-text text-justify mb-2">I wish i was a little bit taller, wish i was a baller, wish i had a girl… also.</p>
                <ul class="list-unstyled nav justify-content-center">
                   <a href="#" class="text-dark text-decoration-none"> <li class="nav-item">Friends <br> <strong>12M</strong></li></a>
                  <a href="#" class="text-dark text-decoration-none"> <li class="nav-item">Enimes <br> <strong>1</strong></li></a> 
                </ul>

            </div>




        </div>


        <div class="card shadow-sm card-left2 mb-4">

            <div class="card-body">

                    <h5 class="mb-3 card-title">About <small><a href="#" class="ml-1">Edit</a></small></h5>

                    <p class="card-text"> <i class="fas fa-calendar-week mr-2"></i> Went to <a href="#" class="text-decoration-none">oh canada</a></p>

                    <p class="card-text"> <i class="fas fa-user-friends mr-2"></i> Become a friend with <a href="#" class="text-decoration-none">obama</a></p>
                    <p class="card-text"> <i class="far fa-building mr-2"></i> Work at <a href="#" class="text-decoration-none">Github</a></p>
                    <p class="card-text"> <i class="fas fa-home mr-2"></i> Live in <a href="#" class="text-decoration-none">San francisco</a></p>
                    <p class="card-text"> <i class="fas fa-map-marker mr-2"></i> From <a href="#" class="text-decoration-none">Seattle, WA</a></p>




            </div>
         




        </div>




        <div class="card shadow-sm card-left3 mb-4">

            <div class="card-body">
                <h5 class="card-title">Photos<small class="ml-2"><a href="#">.Edit </a></small></h5>

                <div class="row">
                    <div class="col-6 p-1">
                        <a href="{% static "img/left1.jpg" %}" data-lightbox="id" ><img src="{% static "img/left1.jpg" %}" alt="img" class="img-fluid my-2"></a>  
                        <a href="{% static "img/left2.jpg" %}"data-lightbox="id"><img src="{% static "img/left2.jpg" %}" alt="img" class="img-fluid my-2"></a>
                        <a href="{% static "img/left3.jpg" %}"data-lightbox="id"><img src="{% static "img/left3.jpg" %}" alt="img" class="img-fluid my-2"></a>

                    </div>


                    <div class="col-6 p-1">
                            <a href="{% static "img/left4.jpg" %}"data-lightbox="id"><img src="{% static "img/left4.jpg" %}" alt="img" class="img-fluid my-2"></a>
                            <a href="{% static "img/left5.jpg" %}"data-lightbox="id"><img src="{% static "img/left5.jpg" %}" alt="img" class="img-fluid my-2"></a>
                            <a href="{% static "img/left6.jpg" %}"data-lightbox="id"><img src="{% static "img/left6.jpg" %}" alt="img" class="img-fluid my-2"></a>

                        </div>

                </div>

            </div>







            </div>




       

        





    </div>





</div>
{% endblock left_column %} {% endcomment %}

user/templates/user/register.html
{% extends "main/base.html" %}
{% load static %}



{% block content %}

        <body>
        <form method="POST" action = "{% url "user:register" %}">
                {% csrf_token %}
                {{ form }}
        <input type="submit" value="Send" >
        <a href="{% url "user:login" %}">Already registred?</a>
       
        </form>
        </body>

{% endblock content %}