api/urls.py
#path('api/load_more/', views.load_more, name='load_more'),
"""
URL configuration for blocks project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.urls import path
from api import views

app_name = "api"

urlpatterns = [
   path('load_more/', views.load_more, name='load_more'),
]

main/urls.py
from django.urls import path, include
from main import views

app_name = "main"

urlpatterns = [
    path("", views.index, name = "index"),
    path("messages/", views.messages, name = "messages"),
]

posts/urls.py
from django.urls import path, include
from posts import views

app_name = "posts"

urlpatterns = [
    path("post/", views.post, name = "post"),
    path("commentary/", views.commentary, name = "commentary"),
    path("follow/", views.follow, name = "follow"),
    path("unfollow/", views.unfollow, name="unfollow"),
    path("post_like/", views.post_like, name="post_like"),
    path("post_unlike/", views.post_unlike, name = "post_unlike"),
]

main/models.py
# from django.db import models

main/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
import requests
from posts.models import Posts
import datetime
from main.utils import generate_jwt_token
from main.caching import *



def index(request):


    user = request.user
    posts = Posts.objects.all().order_by('-posting_time')[:10]
    has_posts = len(posts) > 0

    context = {
        "title":"Лента",
        "posts":posts,
        "has_posts":has_posts,
        "user":user,
    }

    return render(request,"main/index.html", context)



def messages(request):
    
    messages_url = "http://127.0.0.1:8080/"

    if not request.user.is_authenticated:
        #NOT AUTH LOGIC
        return HttpResponseRedirect(reverse("user:login"))
    
    try:
        response = requests.request(url=messages_url, method="GET")
    except:
        #not working logic
        return HttpResponseRedirect(reverse("main:index"))

    token = generate_jwt_token(request.user)
    url = f'http://localhost:8080/auth?token={token}'

    return redirect(url)

main/templates/main/base.html
<!DOCTYPE html>
{% load static %}


<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="stylesheet" href="{% static "main_style.css" %}">
<link rel="stylesheet" href="{% static "all.css" %}">
<link rel="stylesheet" href="{% static "style.css" %}">
<link rel="stylesheet" href="{% static "main/style.css" %}">

<!------------------LIght BOx for Gallery-------------->
<link rel="stylesheet" href="{% static "lightbox.min.css" %}">
<script type="text/javascript" src="{% static "lightbox-plus-jquery.min.js" %}"></script>
<!------------------LIght BOx for Gallery-------------->

{% block title %}

{% endblock title %}

</head>
<body>


    <!-------------------------------NAvigation Starts------------------>

    <nav class="navbar navbar-expand-md navbar-dark mb-4" style="background-color:#3097D1">
        <a href="{% url "main:index" %}" class="navbar-brand"><img src="{% static "img/brand-white.png" %}" alt="logo" class="img-fluid" width="80px" height="100px"></a>

        <button class="navbar-toggler" data-toggle="collapse" data-target="#responsive"><span class="navbar-toggler-icon"></span></button>


        <div class="collapse navbar-collapse" id="responsive">
            <ul class="navbar-nav mr-auto text-capitalize">
                <li class="nav-item"><a href="main:index" class="nav-link active">home</a></li>
                <li class="nav-item"><a href="{% url "user:login" %}" class="nav-link">profile</a></li>
                <li class="nav-item"><a href="{% url "main:messages" %}" class="nav-link">messages</a></li>
                <li class="nav-item"><a href="#" class="nav-link">docs</a></li>
                <li class="nav-item"><a href="#" class="nav-link d-md-none">growl</a></li>
                <li class="nav-item"><a href="#" class="nav-link d-md-none">logout</a></li>

            </ul>

            <form action="" class="form-inline ml-auto d-none d-md-block">
                <input type="text" name="search" id="search" placeholder="Search" class="form-control form-control-sm">
            </form>
            <a href="notification.html" class="text-decoration-none" style="color:#CBE4F2;font-size:22px;"><i class="far fa-bell ml-3 d-none d-md-block"></i></a> 
            
            <a href="{% url "user:logout" %}">
                <img src="{{user.image}}" alt="" class="rounded-circle ml-3 d-none d-md-block" width="32px" height="32px">
            </a>
            




        </div>





    </nav>

    <!---------------------------------------------Ends navigation------------------------------>

    <!---------------------------MOdal Section  satrts------------------->

    {% comment %} <div class="modal fade" id="modalview">
        <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered">

            <div class="modal-content">


                <div class="modal-header">
                    <div class="modal-title h4">Messages</div>

                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>


                <div class="modal-body">


                    <ul class="list-unstyled">


                     <a href="#" class="text-decoration-none">
                        <li class="media hover-media">
                           
                                <img src="img/avatar-dhg.png" alt="img" width="60px" height="60px" class="rounded-circle mr-3">

                                <div class="media-body text-dark">
                                        <h6 class="media-header">Jchob Thunder and <strong> 1 others</strong></h6>
                                        <p class="media-text">Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>

                                </div>

                        </li>
                    </a>
                    <hr class="my-3">


                    
                    <a href="#" class="text-decoration-none">
                            <li class="media hover-media">
                               
                                    <img src="img/avatar-fat.jpg" alt="img" width="60px" height="60px" class="rounded-circle mr-3">
    
                                    <div class="media-body text-dark">
                                            <h6 class="media-header">Mark Otto and <strong> 3 others</strong></h6>
                                            <p class="media-text">Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
    
                                    </div>
    
                            </li>
                        </a>


                        <hr class="my-3">


                        <a href="#" class="text-decoration-none">
                            <li class="media hover-media">
                               
                                    <img src="img/avatar-mdo.png" alt="img" width="60px" height="60px" class="rounded-circle mr-3">
    
                                    <div class="media-body text-dark">
                                            <h6 class="media-header">Archer andu and <strong> 5 others</strong></h6>
                                            <p class="media-text">Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
    
                                    </div>
    
                            </li>
                        </a>

                        <hr class="my-3">


                        <a href="#" class="text-decoration-none">
                                <li class="media hover-media">
                                   
                                        <img src="img/avatar-dhg.png" alt="img" width="60px" height="60px" class="rounded-circle mr-3">
        
                                        <div class="media-body text-dark">
                                                <h6 class="media-header">Jchob Thunder and <strong> 1 others</strong></h6>
                                                <p class="media-text">Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
        
                                        </div>
        
                                </li>
                            </a>
                            <hr class="my-3">
        
        
                            
                            <a href="#" class="text-decoration-none">
                                    <li class="media hover-media">
                                       
                                            <img src="img/avatar-fat.jpg" alt="img" width="60px" height="60px" class="rounded-circle mr-3">
            
                                            <div class="media-body text-dark">
                                                    <h6 class="media-header">Mark Otto and <strong> 3 others</strong></h6>
                                                    <p class="media-text">Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
            
                                            </div>
            
                                    </li>
                                </a>
        
        
                                <hr class="my-3">
        
        
                                <a href="#" class="text-decoration-none">
                                    <li class="media hover-media">
                                       
                                            <img src="img/avatar-mdo.png" alt="img" width="60px" height="60px" class="rounded-circle mr-3">
            
                                            <div class="media-body text-dark">
                                                    <h6 class="media-header">Archer andu and <strong> 5 others</strong></h6>
                                                    <p class="media-text">Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
            
                                            </div>
            
                                    </li>
                                </a>

                        
                                <hr class="my-3">
                                <a href="#" class="text-decoration-none">
                                        <li class="media hover-media">
                                           
                                                <img src="img/avatar-dhg.png" alt="img" width="60px" height="60px" class="rounded-circle mr-3">
                
                                                <div class="media-body text-dark">
                                                        <h6 class="media-header">Jchob Thunder and <strong> 1 others</strong></h6>
                                                        <p class="media-text">Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                
                                                </div>
                
                                        </li>
                                    </a>
                                    <hr class="my-3">
                
                
                                    
                                    <a href="#" class="text-decoration-none">
                                            <li class="media hover-media">
                                               
                                                    <img src="img/avatar-fat.jpg" alt="img" width="60px" height="60px" class="rounded-circle mr-3">
                    
                                                    <div class="media-body text-dark">
                                                            <h6 class="media-header">Mark Otto and <strong> 3 others</strong></h6>
                                                            <p class="media-text">Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                    
                                                    </div>
                    
                                            </li>
                                        </a>
                
                
                                        <hr class="my-3">
                
                
                                        <a href="#" class="text-decoration-none">
                                            <li class="media hover-media">
                                               
                                                    <img src="img/avatar-mdo.png" alt="img" width="60px" height="60px" class="rounded-circle mr-3">
                    
                                                    <div class="media-body text-dark">
                                                            <h6 class="media-header">Archer andu and <strong> 5 others</strong></h6>
                                                            <p class="media-text">Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                    
                                                    </div>
                    
                                            </li>
                                        </a>
    
    


                    </ul>



                    

                </div>
            </div>


        </div>


    </div> {% endcomment %}

    <!-------------------------------MOdal Ends---------------------------->



    <!-------------------------------------------Start Grids layout for lg-xl-3 columns and (xs-lg 1 columns)--------------------------------->


    <div class="container">
        <div class="row">


            <!--------------------------left columns  start-->

            
{% block left_column %}

{% endblock left_column %}





 <!--------------------------Ends Left columns-->





 <!---------------------------------------Middle columns  start---------------->
{% block content %}

{% endblock content %}
<!------------------------Middle column Ends---------------->








{% block right_column %}
{% endblock right_column %}




    




























<!------------------------Light BOx OPtions------------->

<script>
        lightbox.option({
          
        })
    </script>


<!------------------------Light BOx OPtions------------->










<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

main/templates/main/index.html
<!DOCTYPE html>
{% extends "main/base.html" %}
{% load static %}
{% load get_commentaries %}
{% load get_time_difference %}
{% load call %}


{% block title %}
    <title>{{title}}</title>
{% endblock title %}




{% block left_column %}
    <div class="col-12 col-lg-3">

        <div class="left-column">


            <div class="card card-left1 mb-4" >
                <img src="{% static "img/photo-1455448972184-de647495d428.jpg" %}" alt="" class="card-img-top img-fluid">
                <div class="card-body text-center ">
                <h4>Text</h4>
                    

                </div>




            </div>


            <div class="card shadow-sm card-left2 mb-4">

                <div class="card-body">

                        <h5 class="mb-3 card-title">About <small><a href="#" class="ml-1">Edit</a></small></h5>

                        <p class="card-text"> <i class="fas fa-calendar-week mr-2"></i> Went to <a href="#" class="text-decoration-none">oh canada</a></p>

                        <p class="card-text"> <i class="fas fa-user-friends mr-2"></i> Become a friend with <a href="#" class="text-decoration-none">obama</a></p>
                        <p class="card-text"> <i class="far fa-building mr-2"></i> Work at <a href="#" class="text-decoration-none">Github</a></p>
                        <p class="card-text"> <i class="fas fa-home mr-2"></i> Live in <a href="#" class="text-decoration-none">San francisco</a></p>
                        <p class="card-text"> <i class="fas fa-map-marker mr-2"></i> From <a href="#" class="text-decoration-none">Seattle, WA</a></p>




                </div>
            




            </div>




            <div class="card shadow-sm card-left3 mb-4">

                <div class="card-body">
                    <h5 class="card-title">Photos<small class="ml-2"><a href="#">.Edit </a></small></h5>

                    <div class="row">
                        <div class="col-6 p-1">
                            <a href="{% static "img/left1.jpg" %}" data-lightbox="id" ><img src="{% static "img/left1.jpg" %}" alt="img" class="img-fluid my-2"></a>  
                            <a href="{% static "img/left2.jpg" %}"data-lightbox="id"><img src="{% static "img/left2.jpg" %}" alt="img" class="img-fluid my-2"></a>
                            <a href="{% static "img/left3.jpg" %}"data-lightbox="id"><img src="{% static "img/left3.jpg" %}" alt="img" class="img-fluid my-2"></a>

                        </div>


                        <div class="col-6 p-1">
                                <a href="{% static "img/left4.jpg" %}"data-lightbox="id"><img src="{% static "img/left4.jpg" %}" alt="img" class="img-fluid my-2"></a>
                                <a href="{% static "img/left5.jpg" %}"data-lightbox="id"><img src="{% static "img/left5.jpg" %}" alt="img" class="img-fluid my-2"></a>
                                <a href="{% static "img/left6.jpg" %}"data-lightbox="id"><img src="{% static "img/left6.jpg" %}" alt="img" class="img-fluid my-2"></a>

                            </div>

                    </div>

                </div>







                </div>




        

            





        </div>





    </div>


{% endblock left_column %}






{% block content %}
        <script src="{% static "main/endless_scroll.js" %}"></script>

            <!---------------------------------------Middle columns  start---------------->


        <form class = "message_input" metod = "GET" action = "{% url "posts:post" %}">
                    
            <div class="col-28 col-lg-16" >


                <div class="middle-column">


                    <div class="card" id = "card">


                        <div class="card-header bg-transparent">
                            <form class="form-inline">


                                <div class="input-group w-100">
                                <input type="text" name="message" id="message" placeholder="Message" class="form-control form-control-md">

                                <div class="input-group-append">
                                        <div class="input-group-text">
                                                <i class="fas fa-paper-plane"></i>
                                            </div>


                                </div>

                                </div>



                        
                                
                            
                            </form>

                        </div>

        </form>

    


    {% if has_posts %}                           
        {% for post in posts %}

        <div class="card-body" id = "post:{{post.id}}">

            <div class="media">
                <img src="{{post.user.image}}" alt="img" width="60px" height="60px" class="rounded-circle mr-3">
        
            <div class="media-body">
                    <a href="{% url "user:profile" post.user.username %}" class = "username_text">{{post.user.username}}</a>
                    <p class="text-justify">{{post.text}}</p>
                    

                    <div class = "user_actions">

                        <form class = "commentary_input" metod = "GET" action = "{% url "posts:commentary" %}">
                            <div class = "custom_commentary_text">

                                <div class = "like_counter">
                                    <p>{{post.likes}}<p>
                                </div>

                                <div class = "like">
                                    {% call post "is_liked" user as is_liked %}
                                    {% if is_liked %}
                                    <a href="{% url "posts:post_unlike" %}?id={{post.id}}" class="like_button">
                                        <img src = "{% static "main/like_button/red_heart.svg" %}" height = 30px, width = 30px>
                                    </a>
                                    {% else %}
                                        <a href="{% url "posts:post_like" %}?id={{post.id}}" class="like_button">
                                            <img src = "{% static "main/like_button/black_heart.svg" %}" height = 30px, width = 30px>
                                        </a>
                                    {% endif %}
                                </div>

    
                                <input type="text" name="message" id="message" placeholder="Commentary" class="commentary_input_text">
                                <input type="hidden" name="post_id" value="{{post.id}}">
                                
                                
                                
                                <script>
                                    function myFunction(id) {

                                        var posts = document.getElementById('post_commentaries' + id)
                                    
                                        if (posts.style.display == "none"){
                                            posts.style.display = "block"
                                        }else{
                                            posts.style.display = "none"
                                        }
                                    
                                      } 
                                </script>

                                <form>
                                    <button type = "button" class = "comment_button" onclick="myFunction({{post.id}})">
                                        <img src = "{% static "main/comment_button/comment-solid.svg" %}" height = 30px, width = 30px>
                                    </button>
                                </form>
                            </div>
                        </form>
    
                    </div>

                    
                    
                
                <div class = "post_commentaries" id = "post_commentaries{{post.id}}" style="display:none">
                    {% comment %} commentaries {% endcomment %}
                    {% get_commentaries post as commentaries %}
                    <p class = "commentaries">
                        {% for commentary in commentaries %}
                            <div class="media">
                                <img src="{{commentary.user.image}}" alt="img" width="30px" height="30px" class="rounded-circle mr-2">
                                <div class="media-body">
                                        <p class="card-text text-justify">{{commentary.user.username}}: {{commentary.text}}</p>

                                </div>


                            </div>
                        {% endfor %}
                    </p>    
                    {% comment %} commentaries {% endcomment %}

                </div>
            
                

            </div>




            <small>{%get_time_difference post.posting_time%}</small>

            </div>





            </div>
            <hr>

        {% endfor %}

            {% comment %} pagination {% endcomment %}

           
            
            {% comment %}  {% endcomment %}


    {% else %}
    <p>Постов нет<p>
    {% endif %} 


        </div>





                    
                        

        </div>









        </div>








        </div>














{% endblock content %}